debug build

diff --git a/.github/workflows/android14-5.15-custom.yml b/.github/workflows/android14-5.15-custom.yml
--- a/.github/workflows/android14-5.15-custom.yml
+++ b/.github/workflows/android14-5.15-custom.yml
@@ -8,7 +8,7 @@ on:
         type: string
         description: >
           Patch level of common kernel manifest,
-          for example: 2023-011
+          for example: 2024-04
       os_version:
         required: true
         type: string
@@ -43,6 +43,14 @@ jobs:
       run: |
         sudo apt install repo wget -y
 
+    - name: Install latest repo tool
+      run: |
+        curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
+        chmod a+x /usr/local/bin/repo
+
+    - name: Verify repo version
+      run: repo --version
+
     - name: Sync the kernel source code
       run: |
         cd $GITHUB_WORKSPACE
@@ -50,6 +58,7 @@ jobs:
         cd android-kernel
         repo init --depth 1 -u https://android.googlesource.com/kernel/manifest -b common-android14-5.15-${{ inputs.os_patch_level }}
         repo sync
+        ls -la
 
     - name: Apply patches and configuration files
       if: ${{ inputs.custom == true }}
@@ -69,8 +78,29 @@ jobs:
     - name: Build Kernel
       run: |
         cd $GITHUB_WORKSPACE/android-kernel
-        BUILD_CONFIG=common/build.config.gki.aarch64 build/config.sh savedefconfig
-        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
+        echo "ls build"
+        ls build
+        echo "ls build/kernel"
+        ls build/kernel
+        cp build/kernel/_setup_env.sh build/_setup_env.sh
+        echo "ls build"
+        ls build
+        echo "cat after cp:"
+        cat build/_setup_env.sh
+        if [ -f build/_setup_env.sh ]; then
+          BUILD_CONFIG=common/build.config.gki.aarch64 build/config.sh savedefconfig
+          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
+        else
+          echo "Error: build/_setup_env.sh not found"
+          ls build
+          echo "ls ."
+          echo "find . | grep setup_env"
+          find . | grep setup_env
+          ls kernel
+          ls prebuilts
+          ls tools
+          exit 1
+        fi
 
     - name: Prepare artifacts
       id: prepareArtifacts
